//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araba()
        {
            this.Musteri = new HashSet<Musteri>();
            this.Kiralik = new HashSet<Kiralik>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SirketID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Vites { get; set; }
        public string Yakit { get; set; }
        public string Sinif { get; set; }
        public string Konum { get; set; }
        public Nullable<short> Fiyat { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteri> Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralik> Kiralik { get; set; }
    }
}
