//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralik
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TcNo { get; set; }
        public string TelNo { get; set; }
        public string email { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> AlmaTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> ArabaID { get; set; }
        public Nullable<int> MusteriID { get; set; }
    
        public virtual Araba Araba { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
